sudo: required
language: node_js

services:
- docker

before_install:
- sudo apt-get update

install:
- ./setup --skip-golang --skip-hub --skip-docker --skip-keybase
- . .bash_profile

script:
- echo $PATH
- php -r 'echo "Running PHP!";'
- echo '{"hello":"goodbye"}' | jq .

