sudo: required
language: node_js

services:
- docker

before_install:
- sudo apt-get update

install:
- ./setup --ruby-version 2.5.1 --skip-zazu --skip-golang --skip-hub --skip-docker --skip-keybase
- . .bash_profile

script:
- echo $PATH
- which ruby

