#!/usr/bin/env bash

set -e

if [[ -z "$(which vim)" ]] ; then
  echo Vim not installed...skipping.
else
  echo Setting up Vim...
  if [[ ! -f $HOME/.vimrc ]] ; then
    echo symlinking ~/.vimrc
    ln -s $HOME/dotfiles/.vimrc $HOME/.vimrc
  fi

  if [[ ! -d $HOME/.vim/autoload ]] ; then
    echo creating ~/.vim/autoload/
    mkdir -p $HOME/.vim/autoload
  fi

  if [[ ! -d $HOME/.vim/bundle ]] ; then
    echo creating ~/.vim/bundle/
    mkdir -p $HOME/.vim/bundle
  fi

  if [[ ! -d $HOME/.vim/session ]] ; then
    echo creating ~/.vim/session/
    mkdir -p $HOME/.vim/session
  fi

  if [[ -z "$(which git)" ]] ; then
    echo Git is not installed. Skipping Vundle installation.
  else
    if [[ ! -f $HOME/.vim/autoload/plug.vim ]] ; then
      echo Downloading vim-plug...
      curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    fi

    echo Installing vim plugins...
    vim +PlugInstall +qall
  fi
fi

if [[ -z "$(which nvim)" ]] ; then
  echo "Neovim not found. Skipping configuration..."
else
  echo Setting up Neovim...
  if ! [[ -f $HOME/.config/nvim/init.vim ]] ; then
    echo symlinking ~/.config/nvim/init.vim
    mkdir -p $HOME/.config/nvim
    ln -s $HOME/dotfiles/.config/nvim/init.vim $HOME/.config/nvim/init.vim
  fi
fi



echo Linking config files...
if [[ -z "$(which git)" ]] ; then
  echo Git is not installed. Skipping git configs.
else
  echo Configuring git...

  if [[ -z "$(git config --global user.email)" ]] ; then
    git config --global user.email coby@tamayo.email
  fi
  if [[ -z "$(git config --global user.name)" ]] ; then
    git config --global user.name 'Coby Tamayo'
  fi

  if [[ ! -f ~/.gitignore ]] ; then
    ln -s ~/dotfiles/.gitignore ~/.gitignore
  fi
  if [[ ! -f ~/.githelpers ]] ; then
    ln -s ~/dotfiles/.githelpers ~/.githelpers
  fi

  git-config
fi

if [[ -z "$(which tmux)" ]] ; then
  echo tmux is not installed. Skipping tmux configs.
else
  if ! [[ -f ~/.tmux.conf ]] ; then
    ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
  fi

  if ! [[ -f ~/.tmux.local.conf ]] ; then
    echo creating local tmux config
    touch ~/.tmux.local.conf
  fi
fi

echo 'done! 👍 🍅 🍕 🚀 🎸 '
