#!/usr/bin/env bash

set -e

echo setting up vim...
if [[ ! -f $HOME/.vimrc ]] ; then
  echo symlinking ~/.vimrc
  ln -s $HOME/dotfiles/.vimrc $HOME/.vimrc
fi

if [[ ! -f $HOME/.local.vimrc ]] ; then
  echo setting machine-specific .local.vimrc
  touch $HOME/.local.vimrc
fi

if [[ ! -d $HOME/.vim/autoload ]] ; then
  echo creating ~/.vim/autoload/
  mkdir -p $HOME/.vim/autoload
fi

if [[ ! -d $HOME/.vim/bundle ]] ; then
  echo creating ~/.vim/bundle/
  mkdir -p $HOME/.vim/bundle
fi

if [[ ! -d $HOME/.vim/bundle/Vundle.vim ]] ; then
  echo downloading Vundle
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

echo installing all the vim plugins...
vim +PluginInstall +qall



echo linking config files
if [[ ! -f ~/.gitignore ]] ; then
  ln -s ~/dotfiles/.gitignore ~/.gitignore
fi

if [[ ! -f ~/.githelpers ]] ; then
  ln -s ~/dotfiles/.githelpers ~/.githelpers
fi

if [[ ! -f ~/.railsrc ]] ; then
  ln -s ~/dotfiles/.railsrc ~/.railsrc
fi

if [[ -d ~/.hammerspoon ]] && [[ ! -f ~/.hammerspoon/init.lua ]] ; then
  ln -s ~/dotfiles/init.lua ~/.hammerspoon/init.lua
fi

if [[ ! -f ~/.zazurc.json ]] ; then
  ln -s ~/dotfiles/.zazurc.json ~/.zazurc.json
fi

if ! [[ -f ~/.tmux.conf ]] ; then
  ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
fi

if ! [[ -f ~/.tmux.local.conf ]] ; then
  echo creating local tmux config
  touch ~/.tmux.local.conf
fi

echo 'done! 👍 🍅 🍕 🚀 🎸 '
