#!/usr/bin/env bash

set -e

echo setting up vim...
if [[ ! -f $HOME/.vimrc ]] ; then
  echo symlinking ~/.vimrc
  ln -s $HOME/dotfiles/.vimrc $HOME/.vimrc
fi

if [[ ! -f $HOME/.local.vimrc ]] ; then
  echo setting machine-specific .local.vimrc
  touch $HOME/.local.vimrc
fi

if [[ ! -d $HOME/.vim/autoload ]] ; then
  echo creating ~/.vim/autoload/
  mkdir -p $HOME/.vim/autoload
fi

if [[ ! -d $HOME/.vim/bundle ]] ; then
  echo creating ~/.vim/bundle/
  mkdir -p $HOME/.vim/bundle
fi

if [[ ! -d $HOME/.vim/session ]] ; then
  echo creating ~/.vim/session/
  mkdir -p $HOME/.vim/session
fi

if [[ ! -d $HOME/.vim/bundle/Vundle.vim ]] ; then
  echo downloading Vundle
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

if [[ "$(which nvim)" ]] ; then
  echo setting up nvim...
  if ! [[ -f $HOME/.nvimrc ]] ; then
    echo symlinking ~/.nvimrc
    ln -s $HOME/dotfiles/.vimrc $HOME/.nvimrc
  fi

  if ! [[ -L "$HOME/.nvim" ]] && ! [[ -d "$HOME/.nvim" ]] ; then
    echo symlinking ~/.nvim
    ln -s $HOME/dotfiles/.vim $HOME/.nvim
  fi
fi

echo installing all the vim plugins...
vim +PluginInstall +qall



echo linking config files
if [[ ! -f ~/.gitignore ]] ; then
  ln -s ~/dotfiles/.gitignore ~/.gitignore
fi

if [[ ! -f ~/.githelpers ]] ; then
  ln -s ~/dotfiles/.githelpers ~/.githelpers
fi

if [[ ! -f ~/.railsrc ]] ; then
  ln -s ~/dotfiles/.railsrc ~/.railsrc
fi

if ! [[ -f ~/.tmux.conf ]] ; then
  ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
fi

if ! [[ -f ~/.muttrc ]] ; then
  ln -s ~/dotfiles/.muttrc ~/.muttrc
fi

if ! [[ -f ~/.mutt/signature ]] ; then
  mkdir -p ~/.mutt
  ln -s ~/dotfiles/.mutt/signature ~/.mutt/signature
fi

if ! [[ -f ~/.tmux.local.conf ]] ; then
  echo creating local tmux config
  touch ~/.tmux.local.conf
fi

echo 'done! 👍 🍅 🍕 🚀 🎸 '
